# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [3]:
print(np.__version__)

1.16.4


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [12]:
import numpy as np
arr=np.array([[1,2],[7,10]], dtype='float')
#print(arr)
print(arr.size)

[[ 1.  2.]
 [ 7. 10.]]
4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
import numpy as np
arr=np.zeros(10)
print(arr)
arr[4]=1
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
arr=np.arange(10,50,1)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [23]:
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
import numpy as np
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [451]:
import numpy as np
arr=np.array([1,2,0,0,4,0])
for i in range(np.shape(arr)[0]):
    if(arr[i]!=0):
        print(i,end=" ")

0 1 4 

#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
import numpy as np
#arr=np.full((3,3),1,dtype='int')
arr=np.identity(3,dtype='complex')
print(arr)

[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [32]:
import numpy as np
arr=np.random.random((3,3))
print(arr)

[[0.20456948 0.28391933 0.07033858]
 [0.74323265 0.20815539 0.48756401]
 [0.88392396 0.20654886 0.35441852]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
arr=np.random.random((10,10))
print(arr)
print(arr.max())
print(arr.min())
#print(arr.size)

[[0.94504391 0.15074179 0.06955991 0.30437061 0.59403335 0.69959202
  0.69557339 0.98426491 0.65637058 0.82061387]
 [0.84169013 0.63848771 0.73271436 0.80605251 0.7692207  0.27744466
  0.79699138 0.67638093 0.23749925 0.05367294]
 [0.12201959 0.86962881 0.70925556 0.9115285  0.35726033 0.34434496
  0.98362869 0.42782821 0.73869154 0.06483159]
 [0.95979671 0.31688104 0.4164955  0.15337139 0.62547616 0.23637237
  0.67634669 0.0184592  0.95739255 0.95330548]
 [0.30863214 0.05003969 0.65332356 0.43667821 0.37311281 0.41964959
  0.86763095 0.01168761 0.40405594 0.00365414]
 [0.44115932 0.33260788 0.00435598 0.56273685 0.19264837 0.0857508
  0.69816019 0.39548949 0.95614698 0.70899541]
 [0.4326074  0.83836686 0.7750518  0.55123867 0.90746598 0.16268193
  0.06750543 0.38088985 0.58004382 0.87530473]
 [0.67100253 0.79631062 0.34184417 0.53443142 0.30974953 0.17970072
  0.59653849 0.25236159 0.45272654 0.64326726]
 [0.25710361 0.66766722 0.12889633 0.12293177 0.2740528  0.66385359
  0.94154072 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [39]:
arr=np.random.random((1,30))
print(arr.mean())


0.46621726365302796


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
import numpy as np
arr=np.zeros((5,5))
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if(i==0 or j==0 or i==arr.shape[0]-1 or j==arr.shape[1]-1):
            arr[i][j]=1
#print(arr.size(axis=0))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [65]:
import numpy as np
arr=np.ones((5,5))
print("Original matrix:-\n",arr)
arr=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("after adding border\n",arr)

Original matrix:-
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
after adding border
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [80]:
nan
false
false
nan
false
'''print(0*nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
#np.nan in set([np.nan])
print(.3==3*.1)'''

False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [81]:
import numpy as np
arr=np.zeros((5,5))
arr[1][0]=1
arr[2][1]=2
arr[3][2]=3
arr[4][3]=4
'''n=arr.shape[0]
m=arr.shape[1]
if matrix is large we can also do the same operation using nested loops
arr=arr[[1,2,3,4],[0,1,2,3]]'''
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [84]:
import numpy as np
arr=np.ones((8,8))
n=arr.shape[0]
m=arr.shape[1]
for i in range(n):
    for j in range(m):
         if((i%2==0 and j%2==0) or (i%2!=0 and j%2!=0)):
            arr[i][j]=0
print(arr)            

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [461]:
import numpy as np
arr=np.random.randint(0,10,336).reshape(6,7,8)
arr1=arr.flatten()
print(arr1[99])
print(arr)

1
[[[0 8 1 1 1 7 0 5]
  [3 5 2 3 2 5 8 2]
  [5 3 2 7 1 7 2 5]
  [3 5 6 8 4 0 1 5]
  [4 4 9 6 5 5 1 3]
  [1 1 7 0 3 4 1 3]
  [6 5 2 2 0 2 9 7]]

 [[4 8 9 9 8 0 6 2]
  [8 1 1 0 1 3 2 0]
  [6 4 3 8 0 6 5 1]
  [8 1 6 9 6 9 3 5]
  [3 8 8 1 6 7 3 0]
  [0 9 4 1 6 4 3 7]
  [8 5 2 9 5 7 0 9]]

 [[9 4 2 1 1 8 6 5]
  [0 9 1 2 0 9 3 0]
  [1 9 3 5 0 7 9 4]
  [3 4 3 5 8 0 2 1]
  [5 1 8 8 7 3 8 2]
  [2 7 0 4 7 4 3 2]
  [1 5 2 6 3 2 0 3]]

 [[5 2 4 1 9 4 8 0]
  [1 7 0 1 4 2 4 1]
  [6 7 8 4 5 8 7 6]
  [4 6 6 9 9 1 3 3]
  [0 1 7 7 0 3 9 2]
  [3 7 6 2 1 4 5 4]
  [3 5 5 5 2 9 1 8]]

 [[4 5 1 3 6 5 2 9]
  [9 1 1 6 8 1 3 9]
  [4 3 8 4 9 5 9 6]
  [6 8 3 4 8 3 4 8]
  [7 2 6 5 2 4 9 6]
  [5 0 3 0 7 5 8 0]
  [0 7 9 2 8 6 2 1]]

 [[2 5 3 5 9 7 9 8]
  [8 5 9 4 4 2 4 0]
  [8 2 6 1 6 2 8 4]
  [1 2 8 2 7 8 8 4]
  [9 2 6 4 2 6 5 5]
  [9 6 8 6 2 8 4 6]
  [7 0 5 2 5 2 5 6]]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [94]:
import numpy as np
arr=np.array([[0,1],[1,0]])
print(arr)
a=4
repetitions=a
arr=np.tile(arr,repetitions)
b=1
repetitions=(a,b)
arr=np.tile(arr,repetitions)
print(arr)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [98]:
#Normalization is process of converting array elements from their actual value to -1 to 1
import numpy as np
arr=np.random.random((5,5))
arr=arr-arr.mean()
arr=arr/arr.max()
print(arr)

[[-0.14623848 -0.96867039  0.16633959 -0.83133471  0.63076188]
 [ 0.82676816  0.73333539  0.88313643 -0.94327519  1.        ]
 [ 0.62309532 -1.01863721  0.57495522  0.45946666 -0.53795287]
 [-0.4496786  -1.07701157 -0.87001043  0.62756132 -1.17951556]
 [ 0.8469241  -0.02581292  0.87498577  0.59173152 -0.79092341]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [101]:
arr1=np.random.random((5,3))
arr2=np.random.random((3,2))
mul=np.dot(arr1,arr2)
print(mul)

[[0.45482193 0.251778  ]
 [0.40693162 0.18191086]
 [0.15513043 0.09500782]
 [0.72365594 0.55425437]
 [0.52268903 0.24197001]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [122]:
import numpy as np
arr=np.arange(0,10,1)
print(arr)
#arr=np.linspace(0,10,11)
#print(arr)
m=(arr>2) & (arr<8)
arr[m]*=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [108]:
#without importing 2nd argument woill subtract from cumputed sum
#after importing numpy 2nd argument would act as a axis
9
10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [119]:
import numpy as np
Z=np.arange(1,5,1)
print(Z)
print(Z**Z)
#print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z)
True
False
True
True
True
False

[1 2 3 4]
[  1   4  27 256]
[False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[1. 2. 3. 4.]


#### 28. What are the result of the following expressions?

##### ```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [128]:
import numpy as np
arr=np.arange(1,5,1)
print(arr[0])
#print(np.array(0) / np.array(0))
#np.array(0) // np.array(0)
#np.array([np.nan]).astype(int).astype(float)

1


#### 29. How to round away from zero a float array ? (★☆☆)

In [133]:
import numpy as np
arr=np.random.random((5,5))
print(arr)
arr=np.round(arr,2)
#print(arr)
arr=np.round(arr,decimals=2)
print(arr)

[[0.17881305 0.03553564 0.80201371 0.02636968 0.52657127]
 [0.14042119 0.06401273 0.23473173 0.12816326 0.38136942]
 [0.33991065 0.97067891 0.75730865 0.51351591 0.21501806]
 [0.07810584 0.38329458 0.93976036 0.3690407  0.82599222]
 [0.04320253 0.47432403 0.9732783  0.49283279 0.4212652 ]]
[[0.18 0.04 0.8  0.03 0.53]
 [0.14 0.06 0.23 0.13 0.38]
 [0.34 0.97 0.76 0.51 0.22]
 [0.08 0.38 0.94 0.37 0.83]
 [0.04 0.47 0.97 0.49 0.42]]


#### 30. How to find common values between two arrays? (★☆☆)

In [11]:
import numpy as np
arr1=np.random.randint(1,11,10).reshape(5,2)
arr2=np.random.randint(5,13,20).reshape(4,5)
print(np.intersect1d(arr1,arr2))

[ 7  9 10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [17]:
defaults = np.seterr(all="ignore")
arr = np.ones(1) / 0
print(arr)
_ = np.seterr(**defaults)

[inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [18]:
#false because sqrt function does not evaluate in complex numbers and emath does
defaults = np.seterr(all="ignore")
print(np.sqrt(-1)) 
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [151]:
#Here, I am supposing every month has 30 days
'''import numpy as np
# Date month year
arr=np.array([30,10,2019])
print("today",arr)
print("Yesterday ",end="")
m=arr
arr[0]=arr[0]-1
#print(arr)
if(arr[0] <= 0):
    arr[0]=30
    arr[1]-=1
    if(arr[1]<=0):
        arr[1]=12
        arr[2]-=1
print(arr)
arr=m
print("Tomorrow ",end="")
arr[0]+=1
if(arr[0]+1 > 30):
    arr[0]=1
    arr[1]+=1
    if(arr[1]>12):
        arr[1]=1
        arr[2]+=1
print(arr) '''
import numpy as np
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print(yesterday)
Today=np.datetime64('today','D')
print(Today)
Tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(Tomorrow)

2019-10-09
2019-10-10
2019-10-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [155]:
import numpy as np
print('July 2016')
np.arange('2016-07','2016-08',dtype='datetime64[D]')

July 2016


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [156]:
A=4
B=5
print(((A+B)*(-A/2)))

-18.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [165]:
import numpy as np
arr=np.arange(0,6,.66)
arr=np.random.random((1,10))
print(arr)
print(np.round(arr,0))
print(np.around(arr,0))
print(np.rint(arr))
print(np.ceil(arr))
print(np.floor(arr))
print(np.trunc(arr))


[[0.43636017 0.14289646 0.04319174 0.91201329 0.11873926 0.27036306
  0.37519704 0.35387132 0.66585464 0.78191892]]
[[0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [170]:
import numpy as np
arr=np.arange(0,5,1)
#print(arr)
a=5
b=1
repetitions=(a,b)
arr=np.tile(arr,repetitions)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [177]:
import numpy as np
'''arr=np.array([0,1])
a=1
b=5
repetitions=(a,b)
arr=np.tile(arr,repetitions)
print(arr)'''
arr=np.linspace(0,1,12,endpoint=True)[1:-1] # using [1:-1] for printing from 1st value to 2nd last value that is why we write 12 here not 10 becaues 2 indexes we need to avoid
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [184]:
arr=np.random.random(10)
arr=np.sort(arr)[-1:0:-1] # descending order
print(arr)
arr=np.sort(arr) #ascending order
print(arr)

[0.85435313 0.76771599 0.6828347  0.65195568 0.54078221 0.44125956
 0.42609127 0.41421332 0.35158767]
[0.35158767 0.41421332 0.42609127 0.44125956 0.54078221 0.65195568
 0.6828347  0.76771599 0.85435313]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [190]:
arr=np.arange(1,11)
print(np.sum(arr))#in between
print(sum(arr))#slowest method
print(arr.sum()) # fatest method

55
55
55


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [194]:
import numpy as np
A=np.random.random((10))
print(A)
B=np.random.random((10))
print(B)
print(A==B)

[0.44465182 0.56707606 0.80466867 0.1424568  0.16176192 0.43892763
 0.71897547 0.08100528 0.67419299 0.0952412 ]
[0.14244235 0.58208005 0.06955485 0.37831849 0.44347169 0.15711148
 0.69972508 0.32760191 0.76198332 0.94889206]
[False False False False False False False False False False]


#### 43. Make an array immutable (read-only) (★★☆)

In [204]:
import numpy as np
arr=np.array([[1,2],[2,3]])
print(arr)
A=np.array((1,2,3)) #Tuple which is immutable
#A[0][0]=99
print(A)

[[1 2]
 [2 3]]
[1 2 3]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [213]:
import numpy as np
arr=np.random.random((10,2))
n=arr.shape[0]
print("cartisian cordiates:-",arr)
for i in range(n):
    arr[i][0]=np.math.sqrt((arr[i][0] *arr[i][0])+(arr[i][1]*arr[i][1]))
    arr[i][1]=np.sin(arr[i][0])
print("Polar cordinates:-",arr)

cartisian cordiates:- [[0.41806893 0.00141906]
 [0.68157822 0.80970347]
 [0.07171694 0.73417107]
 [0.05581284 0.38700232]
 [0.81371212 0.89579513]
 [0.20703348 0.74763425]
 [0.41514814 0.87100491]
 [0.64736971 0.77652015]
 [0.6517759  0.93277264]
 [0.31820026 0.18101761]]
Polar cordinates:- [[0.41807134 0.40599865]
 [1.05838017 0.87156245]
 [0.73766556 0.67256217]
 [0.39100623 0.38111889]
 [1.21019681 0.93568546]
 [0.77577048 0.70026632]
 [0.96488213 0.82198179]
 [1.01097531 0.84735017]
 [1.13792646 0.90776564]
 [0.36608576 0.35796332]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [214]:
import numpy as np
arr=np.random.random(10)
print(arr)
val=arr.max()
print(val)
index=np.where(val==arr)
arr[index]=0
print(arr)

[0.75050122 0.4455675  0.29619185 0.41394112 0.28268774 0.47604144
 0.44071448 0.28792658 0.99131208 0.35234886]
0.9913120807240824
[0.75050122 0.4455675  0.29619185 0.41394112 0.28268774 0.47604144
 0.44071448 0.28792658 0.         0.35234886]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [216]:
import numpy as np
arr=np.random.random((5,5))
print("Random array:-\n",arr)
Area=arr[[0,1],[0,1]]
print("Area\n",Area)

Random array:-
 [[0.64250432 0.29321027 0.12175667 0.23819161 0.46230483]
 [0.04284752 0.58888899 0.36792365 0.66435832 0.85395746]
 [0.55446733 0.75276399 0.91829321 0.2921386  0.11596596]
 [0.34525415 0.6003131  0.08882502 0.06000447 0.99483477]
 [0.36713789 0.58410968 0.29793948 0.96465379 0.28152014]]
Area
 [0.64250432 0.58888899]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [20]:
X = np.arange(8)
for i in range(8):
    Y = X[i] + 0.5
    C=1/(X[i]-Y)
print(C)

-2.0


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [21]:
import numpy as np
arr=np.random.random(10)
for i in range(arr.shape[0]):
    print(arr[i],end="")
print(arr)    

0.58190500735748470.349710855112848830.42438498006299140.063578441883913260.30045229228275060.29433754661563380.57142694940830030.31088601254241530.0443006018493526940.26354951291205075[0.58190501 0.34971086 0.42438498 0.06357844 0.30045229 0.29433755
 0.57142695 0.31088601 0.0443006  0.26354951]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [319]:
import numpy as np
arr=np.arange(0,11,1)
print(arr)
val=5.67
#print(np.argmin(arr))
print(arr[(np.abs(arr-val)).argmin()])

[ 0  1  2  3  4  5  6  7  8  9 10]
6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [222]:
import numpy as np
arr=np.array([[1,2,'R'],[3,4,'G'],[5,6,'B']])
print(arr)

[['1' '2' 'R']
 ['3' '4' 'G']
 ['5' '6' 'B']]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [226]:
import numpy as np
arr=np.random.random((100,2))
print(arr)

[[0.49227432 0.71596463]
 [0.46509753 0.81941745]
 [0.87587113 0.48819375]
 [0.34645059 0.16502283]
 [0.41448686 0.18514064]
 [0.80240352 0.00697083]
 [0.60620545 0.35280757]
 [0.82559261 0.34114203]
 [0.78272263 0.21879821]
 [0.78123052 0.85659881]
 [0.99062298 0.78066189]
 [0.73034518 0.81662419]
 [0.49698952 0.02621378]
 [0.80511632 0.05829311]
 [0.6841635  0.67955923]
 [0.22607616 0.03147463]
 [0.96840467 0.22022092]
 [0.68473489 0.76949373]
 [0.85759848 0.41915466]
 [0.82046686 0.35892812]
 [0.75293627 0.80152152]
 [0.68015755 0.03213306]
 [0.3321321  0.13289094]
 [0.20200007 0.81639823]
 [0.66616023 0.17123248]
 [0.61314789 0.64956356]
 [0.29249883 0.10370008]
 [0.89511996 0.5655296 ]
 [0.52338883 0.72980258]
 [0.15693588 0.60609844]
 [0.96868783 0.71805207]
 [0.65166393 0.89478524]
 [0.43693694 0.33192234]
 [0.50191842 0.15382621]
 [0.15812333 0.60885877]
 [0.90617113 0.65488152]
 [0.88171547 0.15272047]
 [0.16079388 0.71074397]
 [0.37493517 0.92864867]
 [0.91800395 0.86990579]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [224]:
import numpy as np
arr=np.array([[1.4,2,3.76],[3.54,4,5],[5,6,7]],dtype='float32')
print(arr)
arr=np.int32(arr)
print(arr)

[[1.4  2.   3.76]
 [3.54 4.   5.  ]
 [5.   6.   7.  ]]
[[1 2 3]
 [3 4 5]
 [5 6 7]]


#### 54. How to read the following file? (★★☆)

In [ ]:
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [267]:
from io import StringIO
output=StringIO()
output.write('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
#print(output)
contents = output.getvalue()
print(contents)



1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
Inital value for read buffer


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [271]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print(arr)
for index, val in np.ndenumerate(arr):
    print(index,val)
'''Equivalent programme'''    
print("by equivalent programe")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print("(",i,", ",j,")",arr[i][j])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10
(2, 0) 11
(2, 1) 12
(2, 2) 13
(2, 3) 14
(2, 4) 15
(3, 0) 16
(3, 1) 17
(3, 2) 18
(3, 3) 19
(3, 4) 20
(4, 0) 21
(4, 1) 22
(4, 2) 23
(4, 3) 24
(4, 4) 25
by equivalent programe
( 0 ,  0 ) 1
( 0 ,  1 ) 2
( 0 ,  2 ) 3
( 0 ,  3 ) 4
( 0 ,  4 ) 5
( 1 ,  0 ) 6
( 1 ,  1 ) 7
( 1 ,  2 ) 8
( 1 ,  3 ) 9
( 1 ,  4 ) 10
( 2 ,  0 ) 11
( 2 ,  1 ) 12
( 2 ,  2 ) 13
( 2 ,  3 ) 14
( 2 ,  4 ) 15
( 3 ,  0 ) 16
( 3 ,  1 ) 17
( 3 ,  2 ) 18
( 3 ,  3 ) 19
( 3 ,  4 ) 20
( 4 ,  0 ) 21
( 4 ,  1 ) 22
( 4 ,  2 ) 23
( 4 ,  3 ) 24
( 4 ,  4 ) 25


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [297]:
import numpy as np
arr=np.zeros((5,5))
p=7
np.put(arr,np.random.choice(range(25),p,replace=True),True)
print(arr)

[[1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [305]:
import numpy as np
arr=np.arange(25,dtype='float').reshape((5,5))
print(arr - arr.mean(axis=1, keepdims=True)) #keepdims rehape the array created by arr.mean

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [314]:
import numpy as np
arr=np.random.random(9).reshape((3,3))
arr=arr[(arr[:,2].argsort())]
print(arr)

[[0.31387557 0.39959214 0.07936031]
 [0.81135    0.59641921 0.42813381]
 [0.27150217 0.70472917 0.62677673]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [337]:
import numpy as np
arr=np.arange((25)).reshape((5,5))
arr2=arr.flat[:]
print(arr2)
x=7.93
val=arr2[(np.abs(arr2-x)).argmin()]
print(val)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
8
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [338]:
import numpy as np
A=np.arange(1,4).reshape((1,3))
B=np.arange(4,6).reshape((3,1))
C=A+B

ValueError: cannot reshape array of size 2 into shape (3,1)

#### 63. Create an array class that has a name attribute (★★☆)

In [24]:
#class Name(name)
import numpy as np
#name=np.arr(['Aditya','Abhishek'])
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

NameError: name 'NamedArray' is not defined

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [361]:
import numpy as np
A=np.random.randint(1,10,10)
print(A)
B=np.bincount(A)
print(B)
C=np.ones(10)
print(C)
print(B+C)


[9 2 8 1 8 2 4 6 1 6]
[0 2 2 0 1 0 2 0 2 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 3. 3. 1. 2. 1. 3. 1. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [340]:
A= [1,2,3,4,5,6]
B= [1,3,9,3,4,1]
C=np.bincount(A,B) 
print(C)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [356]:
Z = np.ones(10)
print(Z)
I = np.random.randint(0,len(Z),20)
print(I)
print(np.bincount(I))
Z+= np.bincount(I)
print(Z)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 2 5 0 4 9 2 2 4 4 3 7 9 7 2 8 9 4 5 5]
[1 0 4 1 4 3 1 2 1 3]
[2. 1. 5. 2. 5. 4. 2. 3. 2. 4.]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [37]:
import numpy as np
A=np.random.randint(0,10,2*3*2*3).reshape(2,3,2,3)
print(A)
sum=A.sum(axis=(0,1))
print(sum)

[[[[4 5 7]
   [8 6 9]]

  [[7 0 3]
   [0 4 9]]

  [[1 7 3]
   [2 1 0]]]


 [[[1 5 2]
   [0 5 2]]

  [[5 3 7]
   [8 4 8]]

  [[3 5 2]
   [3 6 5]]]]
[[21 25 24]
 [21 26 33]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [254]:
import numpy as np
A=np.arange(1,26).reshape(5,5)
B=np.arange(26,51).reshape(5,5)
print(A)
print(B)
ans=np.dot(A,B)
print(np.diag(ans))
n=A.shape[0]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[ 590 1530 2520 3560 4650]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [364]:
import numpy as np
arr=np.arange(1,6,1)
print(arr)
j=0
A=np.zeros(len(arr)+(len(arr)-1)*3)
for i in range(0,len(A),4):
    A[i]=arr[j]
    j+=1
print(A)    
        

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [40]:
import numpy as np
A=np.random.random((5,5,3))
B=np.random.random((5,5))
print("A:-\n",A)
print("B:-\n",B)
print((A*B[:,:,None]))


A:-
 [[[0.83125673 0.11134981 0.3988533 ]
  [0.2429109  0.6934061  0.61407231]
  [0.44788708 0.84038887 0.0332287 ]
  [0.14459824 0.65291857 0.26526172]
  [0.86941935 0.68814684 0.3676959 ]]

 [[0.08082503 0.65193957 0.89875703]
  [0.91201037 0.73151598 0.17450778]
  [0.7891269  0.47577633 0.18599702]
  [0.16534499 0.22851823 0.77700998]
  [0.30036057 0.25393241 0.69925317]]

 [[0.69368512 0.5623951  0.19596064]
  [0.10467362 0.44563521 0.05156057]
  [0.36021938 0.23602653 0.90760331]
  [0.02548056 0.20892978 0.75126736]
  [0.26949289 0.74976523 0.36488505]]

 [[0.40445477 0.52463886 0.00295636]
  [0.18212089 0.02557007 0.93470434]
  [0.09697717 0.31702825 0.35378347]
  [0.38577796 0.06822813 0.07825438]
  [0.12766807 0.37407437 0.86561252]]

 [[0.40897495 0.45349074 0.0527812 ]
  [0.60730841 0.24789105 0.6150843 ]
  [0.0484274  0.40540346 0.62785226]
  [0.42044032 0.89316955 0.97663057]
  [0.06713221 0.59260744 0.14470295]]]
B:-
 [[0.46148381 0.19682226 0.09923562 0.81646746 0.0061092

#### 72. How to swap two rows of an array? (★★★)

In [235]:
import numpy as np
import copy
arr=np.random.random((5,5))
print(arr)
#suppose we need to swap row 2 and 3
arr[2]=arr[2]+arr[3]                #4,5 a=a+b 9,5 b=a-b 9,4 a=a-b 5,4
arr[3]=arr[2]-arr[3]
arr[2]=arr[2]-arr[3]
print("After swapping:-\n",arr)
temp=copy.deepcopy(arr[2])#using deep copy
arr[2]=arr[3]
arr[3]=temp
print("After 2nd swapping:-\n",arr)
#for j in range(m)
    

[[0.11469183 0.26725174 0.71374124 0.45591283 0.90735641]
 [0.2848472  0.91551307 0.35534444 0.13453277 0.80862486]
 [0.02801715 0.18312356 0.11636484 0.87355469 0.26534748]
 [0.50505936 0.93686584 0.50000562 0.13637825 0.44205478]
 [0.04292436 0.94392503 0.58372513 0.39003106 0.42073932]]
After swapping:-
 [[0.11469183 0.26725174 0.71374124 0.45591283 0.90735641]
 [0.2848472  0.91551307 0.35534444 0.13453277 0.80862486]
 [0.50505936 0.93686584 0.50000562 0.13637825 0.44205478]
 [0.02801715 0.18312356 0.11636484 0.87355469 0.26534748]
 [0.04292436 0.94392503 0.58372513 0.39003106 0.42073932]]
After 2nd swapping:-
 [[0.11469183 0.26725174 0.71374124 0.45591283 0.90735641]
 [0.2848472  0.91551307 0.35534444 0.13453277 0.80862486]
 [0.02801715 0.18312356 0.11636484 0.87355469 0.26534748]
 [0.50505936 0.93686584 0.50000562 0.13637825 0.44205478]
 [0.04292436 0.94392503 0.58372513 0.39003106 0.42073932]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [383]:
B=np.random.randint(0,10,10)
C=np.bincount(B)
A=B
print(np.bincount(A) == C)
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(C)
print(A)

[0 0 4 9 6 5 5 0 3 2]
[3 0 1 1 1 2 1 0 0 1]
[ True  True  True  True  True  True  True  True  True  True]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [377]:
import numpy as np
arr=np.arange(1,11,1)
print(arr)
s=np.sum(arr[0:3])
print(s/3,end=" ")
n=np.size(arr)
#print(n)
for i in range(4,n):
    s=s+arr[i]-arr[i-3]
    print(s/3,end=" ")
#print(np.mean(arr))

[ 1  2  3  4  5  6  7  8  9 10]
2.0 3.0 4.0 5.0 6.0 7.0 8.0 

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [392]:
import numpy as np
arr=np.random.randint(0,11,10)
print(arr)
arr=-1*arr
print(arr)
a=True
print(~a)

[10  2  6 10  9  7  4  4  9  6]
[-10  -2  -6 -10  -9  -7  -4  -4  -9  -6]
-2


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [397]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
P  = np.random.uniform(-10,10,( 1,2))
print("P0\n",P0)
print("P1\n",P1)
print("P\n",P)
for i in range(10):
    d1=np.math.sqrt((P0[i][0]**2) * (P[0][0]**2)+(P0[i][1]**2) * (P[0][1]**2))
    d2=np.math.sqrt((P1[i][0]**2) * (P[0][0]**2)+(P1[i][1]**2) * (P[0][1]**2))
    print(d1,"   ",d2)

P0
 [[-3.7399341  -7.05238908]
 [-3.63765906 -9.11292168]
 [-6.20510556 -8.71645399]
 [ 3.6737629  -8.02182855]
 [ 9.19934693 -4.49565006]
 [ 0.82359986  7.50723294]
 [ 7.32931745 -6.2041677 ]
 [-7.6609754  -6.97768824]
 [ 2.89349466 -9.02638636]
 [ 3.42784403 -9.43560412]]
P1
 [[ 1.3698254  -8.98461716]
 [-5.98580331 -4.05577496]
 [ 5.38314442 -5.54635297]
 [-7.95998533 -6.69251197]
 [-3.4211454   9.13893673]
 [-9.01111895  4.82516822]
 [-6.0381969  -1.62132377]
 [ 4.87711047  9.6595744 ]
 [-8.28668933  7.65632906]
 [-8.78987293  1.92195723]]
P
 [[-6.49018396  3.85450358]]
36.443273587538016     35.75419226262698
42.32268382369647     41.876398082499435
52.44668911646348     40.95941049308925
39.045669467951164     57.744160483582746
62.16926984663638     41.639970494105285
29.426220701015094     61.3699122593942
53.24145217249338     39.6841703903239
56.52929290899489     48.8694216032924
39.53684923922825     61.346866546777065
42.63437199966351     57.526892055342934


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
P  = np.random.uniform(-10,10,( 1,2))
print("P0\n",P0)
print("P1\n",P1)
print("P\n",P)
for i in range(10):
    d1=np.math.sqrt((P0[i][0]**2) * (P[0][0]**2)+(P0[i][1]**2) * (P[0][1]**2))
    d2=np.math.sqrt((P1[i][0]**2) * (P[0][0]**2)+(P1[i][1]**2) * (P[0][1]**2))
    print(d1,"   ",d2)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [407]:
import numpy as np
arr=np.arange(1,15)
print(arr)
n=arr.shape[0]
print(n)
for i in range(n)
    

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14


#### 82. Compute a matrix rank (★★★)

In [404]:
import numpy as np
arr=np.zeros(10).reshape(5,2)
print(arr)
rank=np.linalg.matrix_rank(arr)
print(rank)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
0


#### 83. How to find the most frequent value in an array?

In [422]:
import numpy as np
arr=np.random.randint(1,10,20)
freq=np.bincount(arr)
val=freq.max()

[6 8 2 8 4 2 4 3 2 6 1 5 7 8 1 1 4 1 3 4]
[0 4 3 2 4 1 2 1 3]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [427]:
import numpy as np
arr=np.random.randint(1,10,100).reshape(10,10)
print(arr)
n=arr.shape[0]
m=arr.shape[1]
for i in range(n-3):
    for j in range(m-3):
        X=arr[i:i+3,j:j+3]
        print(X)

[[5 5 8 2 9 7 3 9 6 9]
 [5 9 3 5 9 3 9 6 1 6]
 [2 3 5 7 9 3 8 1 7 9]
 [9 5 9 6 4 7 8 8 2 9]
 [2 6 4 3 9 5 9 7 5 1]
 [8 7 4 9 4 8 3 3 8 5]
 [6 2 2 1 7 4 2 2 1 2]
 [8 4 8 8 4 9 9 7 9 1]
 [7 5 8 7 7 4 9 4 5 2]
 [9 6 5 1 8 9 6 5 2 9]]
[[5 5 8]
 [5 9 3]
 [2 3 5]]
[[5 8 2]
 [9 3 5]
 [3 5 7]]
[[8 2 9]
 [3 5 9]
 [5 7 9]]
[[2 9 7]
 [5 9 3]
 [7 9 3]]
[[9 7 3]
 [9 3 9]
 [9 3 8]]
[[7 3 9]
 [3 9 6]
 [3 8 1]]
[[3 9 6]
 [9 6 1]
 [8 1 7]]
[[5 9 3]
 [2 3 5]
 [9 5 9]]
[[9 3 5]
 [3 5 7]
 [5 9 6]]
[[3 5 9]
 [5 7 9]
 [9 6 4]]
[[5 9 3]
 [7 9 3]
 [6 4 7]]
[[9 3 9]
 [9 3 8]
 [4 7 8]]
[[3 9 6]
 [3 8 1]
 [7 8 8]]
[[9 6 1]
 [8 1 7]
 [8 8 2]]
[[2 3 5]
 [9 5 9]
 [2 6 4]]
[[3 5 7]
 [5 9 6]
 [6 4 3]]
[[5 7 9]
 [9 6 4]
 [4 3 9]]
[[7 9 3]
 [6 4 7]
 [3 9 5]]
[[9 3 8]
 [4 7 8]
 [9 5 9]]
[[3 8 1]
 [7 8 8]
 [5 9 7]]
[[8 1 7]
 [8 8 2]
 [9 7 5]]
[[9 5 9]
 [2 6 4]
 [8 7 4]]
[[5 9 6]
 [6 4 3]
 [7 4 9]]
[[9 6 4]
 [4 3 9]
 [4 9 4]]
[[6 4 7]
 [3 9 5]
 [9 4 8]]
[[4 7 8]
 [9 5 9]
 [4 8 3]]
[[7 8 8]
 [5 9 7]
 [8 3 3]]
[[8 8 2]
 [9 

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [430]:
class subarr(Z):
    def symmetric(self,Z):
        n=Z.shape[0]
        m=Z.shape[1]
        for i in range(n//2):
            for j in range(m):
                Z[i][j]=Z[j][i]

import numpy as np
Z=np.random.randint(0,10,25).reshape(5,5)
print(Z)
obj=
print(Z)        

[[1 3 8 8 2]
 [0 4 6 3 5]
 [0 5 0 6 3]
 [9 0 4 9 0]
 [4 2 1 2 8]]
[[1 0 0 9 4]
 [0 4 5 0 2]
 [0 5 0 6 3]
 [9 0 4 9 0]
 [4 2 1 2 8]]



#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [431]:
import numpy as np
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
print(M)
print(V)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]
[[[1.]
  [

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [436]:
import numpy as np
arr=np.random.randint(0,10,256).reshape(16,16)
print(arr)
for i in range(16-4):
    for j in range(16):
            print(arr[i:i+4,j:j+4].sum())
            

[[5 0 6 9 9 7 2 3 0 8 9 1 0 8 9 2]
 [6 2 8 1 9 2 5 6 0 7 3 8 2 4 3 7]
 [6 6 5 1 7 5 2 8 0 4 2 2 5 0 9 5]
 [5 6 5 6 5 7 6 3 9 5 5 2 2 6 2 1]
 [8 7 5 2 8 6 0 7 3 5 4 3 3 3 8 1]
 [8 4 2 1 9 9 8 6 3 4 8 9 3 5 6 3]
 [3 2 8 7 9 7 9 7 8 5 2 0 7 0 1 8]
 [6 9 5 2 1 0 1 1 0 9 7 3 1 5 4 3]
 [0 1 2 7 6 6 3 6 4 9 8 2 0 4 0 9]
 [5 0 2 0 3 8 1 4 0 5 4 3 6 6 2 8]
 [6 4 7 7 2 8 1 5 9 4 9 5 0 2 3 5]
 [9 9 3 2 9 4 7 9 6 5 4 5 9 1 3 1]
 [7 8 7 3 5 7 8 0 3 9 6 3 7 8 3 9]
 [4 8 5 6 3 2 4 6 3 8 4 2 8 8 0 8]
 [1 0 9 3 5 6 9 0 0 9 6 4 0 0 2 3]
 [8 5 2 7 6 3 8 3 2 4 2 6 1 4 3 9]]
77
85
92
83
86
65
68
72
65
65
59
63
65
56
38
15
79
83
82
72
86
69
70
71
62
62
54
62
61
49
36
14
77
79
83
82
96
82
73
76
68
66
62
68
62
49
35
10
79
86
96
99
106
98
88
84
75
67
62
60
59
44
30
13
79
81
81
79
88
75
76
79
73
73
63
61
61
47
34
15
67
75
81
85
88
78
83
87
81
77
64
50
59
48
34
23
59
64
73
70
72
65
72
79
69
71
58
44
64
50
35
28
63
58
66
56
56
57
62
84
81
75
65
46
58
51
34
25
64
64
76
74
82
81
78
91
82
78
68
51
59
44
31
23
79
71


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [442]:
import numpy as np
arr=np.random.randint(0,10,10)
print(arr)
arr1=np.sort(arr)
print(arr1)
print(np.size(arr))
n=4
print(arr1[np.size(arr1)-1:np.size(arr1)-1-n:-1])


[5 6 8 9 3 2 4 0 3 2]
[0 2 2 3 3 4 5 6 8 9]
10
[9 8 6 5]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [446]:
import numpy as np
Z=np.random.randint(0,10,50)
print(Z)
A=Z**3
B=np.power(Z,3)
C=Z*Z*Z
print(A)
print(B)
print(C)

[4 9 8 9 2 3 4 4 7 9 6 7 7 8 2 8 4 5 5 4 1 3 9 6 2 1 2 2 8 6 0 8 0 8 7 4 4
 7 9 8 7 9 5 0 0 6 3 7 0 0]
[ 64 729 512 729   8  27  64  64 343 729 216 343 343 512   8 512  64 125
 125  64   1  27 729 216   8   1   8   8 512 216   0 512   0 512 343  64
  64 343 729 512 343 729 125   0   0 216  27 343   0   0]
[ 64 729 512 729   8  27  64  64 343 729 216 343 343 512   8 512  64 125
 125  64   1  27 729 216   8   1   8   8 512 216   0 512   0 512 343  64
  64 343 729 512 343 729 125   0   0 216  27 343   0   0]
[ 64 729 512 729   8  27  64  64 343 729 216 343 343 512   8 512  64 125
 125  64   1  27 729 216   8   1   8   8 512 216   0 512   0 512 343  64
  64 343 729 512 343 729 125   0   0 216  27 343   0   0]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [45]:
import numpy as np
A=np.random.randint(0,10,(10,3))
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if(A[i][0]!=A[i][j]):
            print(A[i][:])
            break;
    

[8 9 9]
[7 4 7]
[1 4 2]
[0 2 8]
[4 7 0]
[6 8 6]
[6 7 1]
[3 5 0]
[4 4 2]
[5 7 2]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [46]:
A=5
print(A.bin())

AttributeError: 'int' object has no attribute 'bin'

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [47]:
import numpy as np
A=np.random.randint(0,10,(5,5))
print(np.unique(A,axis=0))

[[2 9 4 8 8]
 [4 2 5 4 9]
 [7 1 4 6 7]
 [7 9 6 8 4]
 [9 1 4 5 7]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

C= np.sum(A)
D= A * B
E=np.inner(A, B)
F= np.outer(A, B)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)